// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsNOsF_BwLEZTewEhRjcI6x3EyBNR8QLw',
    appId: '1:534806065016:android:1b73e9618f87106f77e28d',
    messagingSenderId: '534806065016',
    projectId: 'business-chat-1382025',
    storageBucket: 'business-chat-1382025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDDZyl2tiNSggl-l7ZXcBcxJC-SANbgRU',
    appId: '1:534806065016:ios:a1e2d22205852f5777e28d',
    messagingSenderId: '534806065016',
    projectId: 'business-chat-1382025',
    storageBucket: 'business-chat-1382025.firebasestorage.app',
    iosBundleId: 'com.example.buisnessChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDDZyl2tiNSggl-l7ZXcBcxJC-SANbgRU',
    appId: '1:534806065016:ios:a1e2d22205852f5777e28d',
    messagingSenderId: '534806065016',
    projectId: 'business-chat-1382025',
    storageBucket: 'business-chat-1382025.firebasestorage.app',
    iosBundleId: 'com.example.buisnessChat',
  );
}
